name: Build Thesis PDF

on:
  push:
    branches:
      - master

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Compile LaTeX Document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: .
          root_file: thesis.tex
          latexmk_shell_escape: true
          extra_system_packages: |
            py3-pygments
            biber
          args: -pdf -latexoption=-interaction=nonstopmode -latexoption=-file-line-error -f
          # Continue on errors to generate PDF even with minor issues
          continue_on_error: true

      - name: Upload LaTeX Logs
        uses: actions/upload-artifact@v4
        with:
          name: latex-logs
          path: |
            thesis.log
            thesis.blg
            thesis.fls
            thesis.fdb_latexmk
            thesis.bcf
            thesis.run.xml
          retention-days: 30

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: thesis-pdf
          path: thesis.pdf
          retention-days: 30

  release:
    needs: build-pdf
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # Always run release step if PDF exists, even if there were warnings
    if: always() && needs.build-pdf.result == 'success' || needs.build-pdf.result == 'failure'
    steps:
      - name: Download PDF Artifact
        uses: actions/download-artifact@v4
        with:
          name: thesis-pdf
          path: .

      - name: Create Release
        if: hashFiles('thesis.pdf') != ''
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: Latest Thesis Build
          body: |
            Automatically generated PDF from commit `${{ github.sha }}`
            Built on: ${{ github.event.created_at }}
            Commit message: ${{ github.event.head_commit.message }}
            
            **Note**: This build may contain warnings. Check the logs for details.
          files: thesis.pdf
          overwrite: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
